siteName: Alabama Hands & Voices
contactEmail: alabamahinfo@gmail.com
phone: "205-677-3136"
address: "P.O. Box 130627, Birmingham, AL 35213"
facebookUrl: https://www.facebook.com/alabamahandsandvoices/
donationButtonLabel: Donate
footerCopyright: "© 2024 Alabama Hands & Voices"
